pub static BUILTIN_STD_EXPORTS: &[(&str, &[&str])] = &[
  ("std/artifact", &["bytes","cid_of_bytes","in","out"]),
  ("std/bytes", &["from_utf8","len","to_utf8"]),
  ("std/codec", &[]),
  ("std/env", &[]),
  ("std/record", &[]),
  ("std/color", &["hueDegrees","hueKey","quantize","rgbToUnit", "hue_report_multi"]),
  ("std/image", &["decode","encodePNG"]),
  ("std/flow", &["pipe"]),
  ("std/fs", &["writeAll"]),
  ("std/grow", &["unfold","unfold_tree"]),
  ("std/hash", &["cid_hex","is_sha256","sha256_bytes","sha256_text"]),
  ("std/http", &["okOr","post"]),
  ("std/int", &["clamp"]),
  ("std/json", &["pathGet","pathSet"]),
  ("std/bytes", &["empty","from_u8_list","len","concat","push_u8","u32be","crc32","adler32"]),
  ("std/png", &["red_1x1"]),
  ("std/list", &["chunk","dedupe_sorted_int","drop","filter","flatMap","fold","get","groupBy","hist_int","map","push","slice","sortBy","sort_by_int_key","sort_int","stableSortBy","take","uniqueBy"]),
  ("std/map", &["get","set"]),
  ("std/null", &["coalesce","guardNotNull"]),
  ("std/option", &["andThen","map","toResult","unwrapOr","unwrapOrElse"]),
  ("std/path", &["joinAll"]),
  ("std/rec", &["empty","get","getOr","getOrErr","has","keys","merge","remove","rename","select","set","update","values"]),
  ("std/result", &["andThen","err","map","mapErr","ok","orElse","unwrapOr","unwrapOrElse"]),
  ("std/schema", &["check"]),
  ("std/str", &["concat","contains","endsWith","join","len","padLeft","padRight","replace","slice","split","startsWith"]),
  ("std/time", &["add","sub"]),
  ("std/trace", &["artifact_in","artifact_out","emit","module_graph"]),
];
